<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Installment-by-installment amortization rows, generated by the loan
     * engine at disbursement time (and pre-viewed by the /loans/quote
     * endpoint). A repayment is split against these rows in order:
     * penalties first, then interest, then principal.
     */
    public function up(): void
    {
        Schema::create('loan_schedules', function (Blueprint $table) {
            $table->id();
            $table->foreignId('loan_id')->constrained()->cascadeOnDelete();
            $table->unsignedInteger('installment_no');
            $table->date('due_date');
            $table->unsignedBigInteger('principal_due');
            $table->unsignedBigInteger('interest_due');
            $table->unsignedBigInteger('total_due');
            $table->unsignedBigInteger('paid_principal')->default(0);
            $table->unsignedBigInteger('paid_interest')->default(0);
            $table->string('status', 10)->default('pending')
                ->comment('pending | paid');
            $table->timestamps();

            $table->unique(['loan_id', 'installment_no']);
            $table->index(['loan_id', 'status', 'due_date']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('loan_schedules');
    }
};
